// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eljikaqbumdqkrssudrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsamlrYXFidW1kcWtyc3N1ZHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjgzODMsImV4cCI6MjA2NzI0NDM4M30.NRze5UW2Sdi3ZLmoVaSEFRm2QG14LsDBRoQRwDj49aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});